CREATE VIEW PRODUTOECOMMERCE AS
SELECT B2_FILIAL AS EMPRESA,B2_LOCAL AS ARMAZEM,CAST(B2_DMOV AS date) AS DATA_MOVIMENTO,B1_COD AS CODIGO_PRODUTO,B1_DESC AS DESCRICAO_PRODUTO,B0_PRV1 AS PRECO_PRODUTO,
CASE WHEN B2_QATU < 4 THEN 0 ELSE ROUND(B2_QATU,0) END  AS ESTOQUE_PRODUTO,B2_ESTVTEX AS ESTOQUE_VTEX,
ISNULL((SELECT SUM(ROUND(B2_QATU,0)) FROM SB2010 B22 WHERE B2_LOCAL = '10' AND B2_FILIAL <> '0111' AND B22.D_E_L_E_T_ = '' AND B22.B2_COD = B1_COD),0) AS ESTOQUE_GERAL_ARMAZEM_10,
M0_CGC AS CGC_FILIAL,
B2.R_E_C_N_O_ AS REC
FROM SB1010 (NOLOCK) B1
INNER JOIN SB0010 (NOLOCK) B0 ON B0_COD = B1_COD
INNER JOIN SB2010 (NOLOCK) B2 ON B1_COD = B2_COD
INNER JOIN SYS_COMPANY (NOLOCK) SYS_COMPANY ON M0_CODFIL = B2_FILIAL
WHERE B1.D_E_L_E_T_ = '' AND B0.D_E_L_E_T_ = '' AND B2.D_E_L_E_T_ = '' AND SYS_COMPANY.D_E_L_E_T_ = '' AND B1_TIPO = 'ME'
AND B1_COD LIKE '%[0-9]%' AND B1_COD not like '%[:]%' AND B1_COD not like '%-%' AND B1_COD not like '%/%'
AND B1_COD not like '%[A-Z]%' 