server:
  port: 8080

spring:
  application:
    name: cdnet-integrator

  cloud:
    config:
      request-read-timeout: 30000
      request-connect-timeout: 30000
      retry:
        max-attempts: 5

  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:sqlserver://${MSSQLDB_HOST:192.168.0.61}:${MSSQLDB_PORT:1433};databaseName=${MSSQLDB_DBNAME:PROTHEUS};trustServerCertificate=false;encrypt=false;
    username: ${MSSQLDB_USERNAME:sa}
    password: ${MSSQLDB_PASSWORD:Panopreto121930}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.SQLServer2012Dialect

  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: true
    baseline-version: 0
    table: flyway_schema_history_cdnet_integrator


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans,env
  endpoint:
    health:
      show-details: always

schedulers:
  default-most-lock-time: PT30M

update-product:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${UPDATE_PRODUCT_CRON_VALUE:0 */30 5-8 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200

update-purchase:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${UPDATE_PURCHASE_CRON_VALUE:0 */30 16-17 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200

update-ecommerce-inventory:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${UPDATE_ECOMMERCE_INVENTORY_CRON_VALUE:0 */10 8-19 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200

update-inventory:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${UPDATE_INVENTORY_CRON_VALUE:0 */1 1-7 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200

update-sale:
  max-retires: 10
  pulse-interval: 5
  scheduler:
    cron-value: ${UPDATE_SALE_CRON_VALUE:0 */10 1-5 * * *}
    least-lock-time: PT30s
    most-lock-time: PT1M
    limit-rows: 200


cdnet:
  grant-type: ${CDNET_GRANT_TYPE:password}
  client-id: ${CDNET_CLIENT_ID:17-ALMEIDA-ELZA}
  username: ${CDNET_USER:REST}
  password: ${CDNET_PASS:A121930@}
  client-secret: ${CDNET_CLIENT_SECRET:b3e82ac0-64d2-4a57-9879-a1441c0b6b36}
  authentication-server-url: ${CDNET_AUTH_URL:https://login.rommanel.com.br}
  base-server-url: ${CDNET_BASE_URL:https://distribuidor.cdnetweb.com.br}
  base-product-url: ${CDNET_BASE_PRODUCT_URL:https://produto.cdnetweb.com.br}
  base-purchase-url: ${CDNET_BASE_PRODUCT_URL:https://pedido.cdnetweb.com.br}
  base-product-photo-url: ${CDNET_BASE_PRODUCT_PHOTO_URL:https://storage.googleapis.com}
  base-protheus-url: ${CDNET_BASE_PROTHEUS_URL:http://192.168.0.5:9095}
  loggerLevel: BASIC
  inventory:
    ecommerce-company-code: ${CDNET_ECOMMERCE_COMPANY:0118}
    ecommerce-warehouse-code: ${CDNET_ECOMMERCE_WAREHOUSE:01}

togglz:
  console:
    enabled: true
    secured: false
    path: /togglz-console
    use-management-port: false
  features:
    PRODUCT_INVENTORY_ONLY_OUT_OF_SYNC:
      enabled: true
    PRODUCT_FULL_SYNC:
      enabled: false
config:
  client:
    maxAttempts: 3
    backOffDelay: 3000

feign:
  client:
    config:
      default:
        readTimeout: 30000
        connectTimeout: 30000
        loggerLevel: BASIC
