CREATE VIEW INTEGRACAO_CDNET_SALES AS
SELECT LTRIM(RTRIM(F2_FILIAL)) AS EMPRESA,LTRIM(RTRIM(F2_DOC)) AS DOCUMENTO,LTRIM(RTRIM(F2_SERIE)) AS SERIE,LTRIM(RTRIM(F2_CHVNFE)) AS CHAVE,F2_ZDTCDNE AS DATA_INTEGRACAO,F2_ZHRCDNE AS HORA_INTEGRACAO,CAST(F2_EMISSAO AS DATETIME) AS DATA_EMISSAO,
LTRIM(RTRIM(A1_CGC)) AS CGC,F2.R_E_C_N_O_ AS REC
FROM SF2010 (NOLOCK)  F2
INNER JOIN SA1010 (NOLOCK) A1 ON
A1_COD = F2_CLIENTE AND A1_LOJA = F2_LOJA
WHERE F2_ZDTCDNE = '' AND F2.D_E_L_E_T_ = '' AND A1.D_E_L_E_T_ = ''